#!/usr/bin/env bash
# Script that transfers a file from our client to a server

# Check if all parameters are provided
if [ $# -lt 4 ]; then
 echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 exit 1
fi

# Define variables from parameters
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer the file using scp
# '-o StrictHostKeyChecking=no' allows the script to connect to a new server without requiring manual approval of the server's host key
# '-i "$ssh_key"' specifies the private key file to use for authentication
# "$file_path" is the local file to transfer
# "$username@$server_ip:~/" is the remote location to transfer the file to, in the format 'username@server_ip:destination_path'
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"

exit 0
