#!/usr/bin/env bash

# Disable shellcheck warning for an unused variable
# that will be used later in the script
# shellcheck disable=SC2154

# Update package information and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Allow incoming HTTP traffic through UFW for Nginx
sudo ufw allow 'Nginx HTTP'

# Set the default content for the Nginx default page
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

# Configure Nginx to redirect requests to a specific URL
redirect_config="listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.youtube.com\/;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$redirect_config/" /etc/nginx/sites-enabled/default

# Create a custom 404 error page and configure Nginx to use it
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
error_config="listen 80 default_server;\\nerror_page 404 \/404.html;\\n\\tlocation = \/404.html {\\n\\t\\troot \/usr\/share\/nginx\/html;\\n\\t\\tinternal;\\n\\t}"
sudo sed -i "s/listen 80 default_server;/$error_config/" /etc/nginx/sites-enabled/default

# Add a custom header to Nginx configuration indicating the server's hostname
header_config="http {\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$header_config/" /etc/nginx/nginx.conf

# Start the Nginx service
sudo service nginx start
