#!/usr/bin/env bash

# Remove the default Nginx configuration for port 80
rm /etc/nginx/sites-enabled/default

# Create a symbolic link for the default Nginx configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
service nginx restart

